### ISSUE TITLE
undead mobs don't take damage

### ISSUE THREAD

**Issue by Bokev29** [MinecraftschurliMods/Ars-Magica-Legacy#264] opened 2022-02-20 17:55 UTC
with a projectile - physical damage spell undead mobs are unkillable

**Comment by Minecraftschurli** [comment] 2022-02-21 19:57
I can't reproduce this bug please provide more information

**Comment by IchHabeHunger54** [comment] 2022-04-21 14:02
Can't reproduce, might as well already have been fixed without us taking notice of this issue.

**Closed as completed by IchHabeHunger54** 2022-04-21 14:02 UTC
Labels: bug
