### ISSUE TITLE
Obelisk not burning vinteum or liquid essence

### ISSUE THREAD

**Issue by Thepigemperor2** [MinecraftschurliMods/Ars-Magica-Legacy#425] opened 2023-10-27 13:11 UTC
### Describe the bug

I tried putting vinteum or liquid essence buckets into an obelisk but nothing happened. When I exited the obelisk window, the item placed into the obelisk's slot was returned into my inventory but was invisible until my inventory was interacted with. The obelisk also broke instantly regardless of tool involved, and did not drop itself.

This happened on an Aternos multiplayer server

### Steps to Reproduce

1. Place obelisk
2. Try putting vinteum into the obelisk
3. Exit the obelisk and interact with your inventory
4. The obelisk doesn't do anything

### Expected behavior

I was expecting the obelisk to activate and produce etherium when I placed the vinteum inside, and not break instantly regardless of tool in my hand without dropping itself.

### Version

1.19.2-1.3.0

### Forge Version

43.3.0

### Other Mods

- ars_nouveau-1.19.2-3.21.2
- domum_ornamentum-1.19-1.0.143
- aether-1.19.2-1.0.0-beta.1.2-forge
- aeroblender-r1.19.2-1.0
- arsarmiger-1.19.2-1.6.0
- ars_creo-1.19.2-3.2.1
- arsmagicalegacy-1.19.2-1.3.0
- art_of_forging-1.6.7-1.19.2
- biomancy-forge-1.19.2-2.2.0.0
- blockui-1.19.2-0.0.99-ALPHA
- create-1.19.2-0.5.1.e
- createbigcannons-forge-1.19.2-0.5.2.a
- createaddition-1.19.2-1.1.1
- create-stuff-additions1.19.2_v2.0.4a
- alloyed-1.19.2-v1.5a
- Steam_Rails-1.5.1+forge-mc1.19.2
- create-structures-0.1.0
- curios-forge-1.19.2-5.1.4.1
- deep_aether-1.19.2-1.0.0
- deeperdarker-forge-1.19.2-1.2.2
- DivineRPG-1.9.6.9
- eidolon-0.3.6
- geckolib-forge-1.19-3.1.40
- immersive_aircraft-0.6.2+1.19.2-forge
- Jade-1.19.1-forge-8.9.1
- journeymap-1.19.2-5.9.7-forge
- jei-1.19.2-forge-11.6.0.1018
- l2library-1.9.8
- lodestone-1.19.2-1.4.2
- malum-1.19.2-1.5.0.3
- Mekanism-1.19.2-10.3.9.13
- MekanismAdditions-1.19.2-10.3.9.13
- MekanismGenerators-1.19.2-10.3.9.13
- MekanismTools-1.19.2-10.3.9.13
- minecolonies-1.19.2-1.1.266-BETA
- modulargolems-1.9.4
- ModularPowersuits-1.19.2-2.3.5
- multipiston-1.19.2-1.2.25-ALPHA
- mutil-1.19.2-5.1.0
- omnis-1.19.2-1.4.1
- Patchouli-1.19.2-77
- ProjectExpansion-1.19.2-1.0.10
- ProjectE-1.19.2-PE1.0.1B
- ProjectExtended-1.19.2-1.4.0
- secrets_of_forging_revelations-1.2.1-1
- structurize-1.19.2-1.0.661-RELEASE
- TerraBlender-forge-1.19.2-2.0.1.166
- tetra-1.19.2-5.5.1
- tetranomicon-1.4.2-1.19.2
- The_Undergarden-1.19.2-0.8.3
- Undergarden-Tetra Patch-1.3.2-1.19.2
- witheringboon-1.7.15

### Log

```shell
https://mclo.gs/MVxN2Mm
```

**Comment by Minecraftschurli** [comment] 2023-10-28 09:33
I can confirm the instant breaking and I put it on the list for the next update, but the not working is weird because I tested that.

**Comment by Minecraftschurli** [comment] 2023-10-28 09:34
@IchHabeHunger54 please investigate

**Comment by IchHabeHunger54** [comment] 2023-10-30 00:04
Yeah, that's about what I get too. Breaking is fixed in-dev, but the not burning vinteum is weird and I can't reproduce that one. Can I ask you to try and get that bug with only Ars Magica: Legacy, and if that does not work, adding back mods until you find out which mod causes the issue?

**Comment by Thepigemperor2** [comment] 2023-10-30 14:03
I tested it with the exact same mod list in singleplayer and the obelisk worked fine (minus the instant breaking issue). I think the problem is aternos then.

**Comment by Minecraftschurli** [comment] 2023-10-30 14:15
test it on a different server, it could be a server issue

**Comment by Thepigemperor2** [comment] 2023-11-03 12:04
I tested it on another aternos server with the same modlist and it still didn't work. I unfortunately don't have the resources to test it on any other server provider though, sorry

**Closed as completed** 2023-11-17 12:39 UTC
Labels: bug, fixed in dev, verified
